apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ticket-booking
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticket-dev-397920
  artifacts:
    - image: gcr.io/ticket-dev-397920/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
